- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: httpd

  - name: Install Unzip unpacker
    yum:
      name: unzip
      state: latest

  - name: Fetch template archive
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page281/john-doe.zip
      dest: /tmp/
      remote_src: yes

  - name: Copy template files to the server /var/www/html
    copy:
      src: /tmp/johndoe/public_html/
      dest: /var/www/html/
      remote_src: yes

  - name: Server restart
    service:
      name: httpd
      state: restarted
      